# Generated by Django 5.2.3 on 2025-06-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=50)),
                ('days', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.TextField()),
            ],
        ),
    ]
