# Generated by Django 5.2.3 on 2025-06-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_job_center_receive_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='handover_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Returned', 'Item has returned')], default='Pending', max_length=20),
        ),
    ]
