# Generated by Django 5.2.3 on 2025-06-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_borrow_handover_date_borrow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('center_name', models.CharField(max_length=100)),
                ('details_given_by', models.CharField(max_length=100)),
                ('area_manager', models.CharField(max_length=100)),
                ('testing_lane_1_pc', models.CharField(blank=True, choices=[('Desktop', 'Desktop'), ('Mini PC', 'Mini PC'), ('HP', 'HP'), ('Eswis', 'Eswis')], max_length=20, null=True)),
                ('testing_lane_1_monitor', models.BooleanField(default=False)),
                ('testing_lane_2_pc', models.CharField(blank=True, choices=[('Desktop', 'Desktop'), ('Mini PC', 'Mini PC'), ('HP', 'HP'), ('Eswis', 'Eswis')], max_length=20, null=True)),
                ('testing_lane_2_monitor', models.BooleanField(default=False)),
                ('testing_lane_3_pc', models.CharField(blank=True, choices=[('Desktop', 'Desktop'), ('Mini PC', 'Mini PC'), ('HP', 'HP'), ('Eswis', 'Eswis')], max_length=20, null=True)),
                ('testing_lane_3_monitor', models.BooleanField(default=False)),
                ('registration_lane_pc', models.CharField(blank=True, choices=[('Desktop', 'Desktop'), ('Mini PC', 'Mini PC'), ('HP', 'HP'), ('Eswis', 'Eswis')], max_length=20, null=True)),
                ('registration_lane_monitor', models.BooleanField(default=False)),
                ('certificate_lane_pc', models.CharField(blank=True, choices=[('Desktop', 'Desktop'), ('Mini PC', 'Mini PC'), ('HP', 'HP'), ('Eswis', 'Eswis')], max_length=20, null=True)),
                ('certificate_lane_monitor', models.BooleanField(default=False)),
                ('backup_pc', models.CharField(blank=True, choices=[('Desktop', 'Desktop'), ('Mini PC', 'Mini PC'), ('HP', 'HP'), ('Eswis', 'Eswis')], max_length=20, null=True)),
                ('backup_monitor', models.BooleanField(default=False)),
                ('fingerprint_machines', models.PositiveIntegerField(default=0)),
                ('backup_fingerprint_machines', models.PositiveIntegerField(default=0)),
                ('ups', models.PositiveIntegerField(default=0)),
                ('backup_ups', models.PositiveIntegerField(default=0)),
                ('wingles', models.PositiveIntegerField(default=0)),
                ('backup_wingles', models.PositiveIntegerField(default=0)),
                ('dongles', models.PositiveIntegerField(default=0)),
                ('backup_dongles', models.PositiveIntegerField(default=0)),
                ('octopuses', models.PositiveIntegerField(default=0)),
                ('backup_octopuses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
