# Generated by Django 5.2.3 on 2025-07-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_add_remark_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupplan',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
